# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/tempcontrol.xdc

# Block Designs: bd/zynq/zynq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq || ORIG_REF_NAME==zynq} -quiet] -quiet

# IP: bd/zynq/ip/zynq_zynq_ultra_ps_e_0_1/zynq_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==zynq_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/zynq/ip/zynq_led_fade_blink_0_1/zynq_led_fade_blink_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_led_fade_blink_0_1 || ORIG_REF_NAME==zynq_led_fade_blink_0_1} -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/LEDFanPin/tes1/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_zynq_ultra_ps_e_0_1/zynq_zynq_ultra_ps_e_0_1_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/LEDFanPin/tes1/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_zynq_ultra_ps_e_0_1/zynq_zynq_ultra_ps_e_0_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==zynq_zynq_ultra_ps_e_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/LEDFanPin/tes1/projectFPGA.gen/sources_1/bd/zynq/zynq_ooc.xdc
